version: "3.9"

services:
  api:
    build:
      context: ./server-test
      dockerfile: Dockerfile
      # target: production
      # args:
      #   NODE_ENV: production
    image: rarias1082/modular-express-redis-mysql:local  # name/tag the built image
    container_name: api
    restart: unless-stopped
    env_file:
      - ./server-test/.env.docker
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      # ensure your api image has wget/curl installed, or switch to CMD-SHELL with `|| exit 1`
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:8080/api/health || exit 1"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 20s

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20

  mysql:
    image: mysql:8.4
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - mysqldata:/var/lib/mysql
      - ./server-test/sql/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -prootpass"]
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 20s

  web:
    build:
      context: ./react-client
      # these are Docker build args; expose them in your web Dockerfile as ARG/ENV so Vite sees them
      args:
        VITE_API_URL: /api
        VITE_CSRF_PATH: /csrf
        VITE_REGISTER_PATH: /register
        VITE_LOGIN_PATH: /login
    container_name: web
    depends_on:
      api:
        condition: service_healthy
    ports:
      - "8081:80"

volumes:
  redisdata:
  mysqldata:
