name: Build and Push Client Image

on:
  push:
    branches: [ main, master , kube-cluster]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: rarias1082/root-web:latest
          build-args: |
            VITE_API_URL=/api
            VITE_CSRF_PATH=/csrf
            VITE_REGISTER_PATH=/register
            VITE_LOGIN_PATH=/login